// <auto-generated />
using System;
using MarketPlaceApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarketPlaceApi.Migrations
{
    [DbContext(typeof(MarketPlaceContext))]
    [Migration("20190501095503_fixed-column")]
    partial class fixedcolumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarketPlaceApi.Models.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BuildingId");

                    b.Property<Guid?>("ClientId");

                    b.Property<string>("DeviceIdentifier");

                    b.Property<string>("IpAddress");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("MarketPlaceApi.Models.Entities.Point", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddedBy");

                    b.Property<bool?>("Archive");

                    b.Property<string>("AssetId");

                    b.Property<string>("Description");

                    b.Property<Guid?>("DeviceId");

                    b.Property<DateTime?>("LastUpdated");

                    b.Property<string>("Name");

                    b.Property<string>("ObjectId");

                    b.Property<string>("ObjectType");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("MarketPlaceApi.Models.Entities.Point_Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("OrderId");

                    b.Property<Guid?>("PointId");

                    b.HasKey("Id");

                    b.HasIndex("PointId");

                    b.ToTable("Point_Priorities");
                });

            modelBuilder.Entity("MarketPlaceApi.Models.Entities.Trend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<int?>("Interval");

                    b.Property<string>("Name");

                    b.Property<int?>("TimeOut");

                    b.Property<int?>("TreadsNumber");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Trends");
                });

            modelBuilder.Entity("MarketPlaceApi.Models.Entities.Trend_Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("EndDateTime");

                    b.Property<int?>("ErrorCount");

                    b.Property<string>("Notifications");

                    b.Property<int?>("PointCounts");

                    b.Property<DateTime?>("StartDateTime");

                    b.Property<int?>("TimeOutCounts");

                    b.Property<Guid?>("TrendId");

                    b.HasKey("Id");

                    b.HasIndex("TrendId");

                    b.ToTable("Trend_Events");
                });

            modelBuilder.Entity("MarketPlaceApi.Models.Entities.Trend_Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("PointId");

                    b.Property<Guid?>("TrendId");

                    b.HasKey("Id");

                    b.HasIndex("PointId");

                    b.HasIndex("TrendId");

                    b.ToTable("Trend_Points");
                });

            modelBuilder.Entity("MarketPlaceApi.Models.Entities.Point", b =>
                {
                    b.HasOne("MarketPlaceApi.Models.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");
                });

            modelBuilder.Entity("MarketPlaceApi.Models.Entities.Point_Priority", b =>
                {
                    b.HasOne("MarketPlaceApi.Models.Entities.Point", "Point")
                        .WithMany()
                        .HasForeignKey("PointId");
                });

            modelBuilder.Entity("MarketPlaceApi.Models.Entities.Trend_Event", b =>
                {
                    b.HasOne("MarketPlaceApi.Models.Entities.Trend", "Trend")
                        .WithMany()
                        .HasForeignKey("TrendId");
                });

            modelBuilder.Entity("MarketPlaceApi.Models.Entities.Trend_Point", b =>
                {
                    b.HasOne("MarketPlaceApi.Models.Entities.Point", "Point")
                        .WithMany()
                        .HasForeignKey("PointId");

                    b.HasOne("MarketPlaceApi.Models.Entities.Trend", "Trend")
                        .WithMany()
                        .HasForeignKey("TrendId");
                });
#pragma warning restore 612, 618
        }
    }
}
